name: Release

on: 
  release:
    types:
      - "created"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        include:
          - goos: darwin
            osname: macos
          - goos: linux
            osname: linux
          - goos: windows
            osname: windows
            ext: .exe
        exclude:
          - goos: darwin
            goarch: "386"
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -v -ldflags="-X 'main.version=${{github.ref_name}}' -X 'main.vcsHash=${{github.sha}}'" -o ./dsdii-assembler-${{ matrix.osname }}-${{ matrix.goarch }}${{ matrix.ext }} .

    - name: Upload Release Binary
      uses: softprops/action-gh-release@v1
      with:
        files: dsdii-assembler-${{ matrix.osname }}-${{ matrix.goarch }}${{ matrix.ext }}
